[build]
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/a"
  to = "/.netlify/functions/a_stock_moneyflow"
  status = 200

[[redirects]]
  from = "/api/us"
  to = "/.netlify/functions/us_stock_sectors"
  status = 200
